FROM ubuntu:latest
RUN apt update
RUN apt install -y iputils-ping
RUN apt install -y dnsutils
RUN apt install -y traceroute
RUN apt install -y nmap
RUN apt install -y arp-scan
RUN apt install -y mtr-tiny
RUN apt install -y curl