apiVersion: apps/v1
kind: Deployment
metadata:
  name: motd
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: motd
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: motd
    spec:
      automountServiceAccountToken: false # disable service account token, so that the pod can't access the API from Kubernetes itself
      containers:
        - name: motd
          image: localhost:5000/js-motd-kubernetes-example:latest
          env:
            - name: PORT
              value: "3333"
          ports:
            - name: port # lowercase! and only a-z, 0-9, and - are allowed
              containerPort: 3333
