apiVersion: apps/v1
kind: Deployment
metadata:
  name: motd
  namespace: containerwiese
spec:
  selector:
    matchLabels:
      app: motd
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # 1 pod more than the desired number of pods (for update...)
      maxUnavailable: 0 # 0 pods less than the desired number of pods (for update...)
  template: # template for the pods
    metadata:
      labels:
        app: motd
    spec:
      automountServiceAccountToken: false # disable service account token, so that the pod can't access the API from Kubernetes itself
      containers:
        - name: motd
          image: localhost:5000/js-motd-kubernetes-example:latest
          env:
            - name: PORT
              value: "4242"
          ports:
            - name: port
              containerPort: 4242
          # imagePullPolicy: Always # always pull the image, even if it's already there
          # imagePullSecrets: # pull secret for private registry
          #   - name: dockerhub
          resources:
            limits: # maximum resources allowed
              cpu: "420m" # 500 millicpu = 0.5 cpu, 1000 millicpu = 1 cpu
              memory: "420Mi"
            requests: # minimum resources required
              cpu: "42m"
              memory: "42Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: port
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: port
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
