FROM node:alpine AS baseimage
USER node

#-----
# Install dependencies
FROM baseimage AS buildimage
COPY --chown=node:node package*.json /home/node/app/
RUN cd /home/node/app && npm install
COPY --chown=node:node . /home/node/app

#-----
FROM baseimage
COPY --from=buildimage --chown=node:node /home/node/app /home/node/app
CMD ["node", "/home/node/app/index.js"]
