FROM node:alpine as baseImage
USER node

#-----
# Install dependencies
FROM baseImage as buildImage
COPY --chown=node:node package*.json /home/node/app/
RUN cd /home/node/app && npm install
COPY --chown=node:node . /home/node/app

#-----
FROM baseImage
COPY --from=buildImage --chown=node:node /home/node/app /home/node/app
CMD ["node", "/home/node/app/index.js"]
